# Generated by Django 3.2.9 on 2023-06-20 07:18

import custom.utils_upload
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('pob', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fatin Moris')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Data Moris')),
                ('sex', models.CharField(blank=True, choices=[('Mane', 'Mane'), ('Fato', 'Feto')], max_length=6, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=custom.utils_upload.upload_profile, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])], verbose_name='Upload Imajen')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
