# Generated by Django 4.2.3 on 2023-08-09 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('Mane', 'Mane'), ('Feto', 'Feto')], max_length=6, null=True),
        ),
        migrations.CreateModel(
            name='AuditSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tabela')),
                ('action', models.CharField(blank=True, max_length=50, null=True, verbose_name='Asaun')),
                ('before', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dados Antes')),
                ('after', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dados Depois')),
                ('id_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLogin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audituserlogin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
