# Generated by Django 4.2.3 on 2023-09-10 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kuantidadeekipamentu',
            name='ekipamentu',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kuantekipamentu', to='equipments.ekipamentu'),
        ),
    ]
