# Generated by Django 4.2.3 on 2023-10-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_alter_kuantidadeekipamentu_ekipamentu'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizaekipamentu',
            name='data_atu_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Data atu entrega'),
        ),
    ]
