# Generated by Django 4.2.3 on 2023-10-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_utilizaekipamentu_total_loron_atu_uza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizaekipamentu',
            name='kondisaun',
            field=models.CharField(blank=True, choices=[('Diak', 'Diak'), ('Aat', 'Aat')], max_length=10, null=True, verbose_name='Kondisaun Depois Uza'),
        ),
    ]
