# Generated by Django 4.2.3 on 2023-11-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0006_labinventory_alter_utilizaekipamentu_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labinventory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='LabInventory'),
        ),
    ]
