# Generated by Django 4.2.3 on 2023-11-18 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0007_labinventory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='labinventorytransaction',
            name='utilizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilizadorinventaria', to='equipments.utilizador'),
        ),
    ]
